### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bitdivision** [bbaldino/SDPy#1]
Hi,

Do you have any licensing information for this?

Thanks

**Comment by bbaldino** [comment]
just added an MIT license.  also, let me know what you run into.  i haven't touched this in a while but would love to try and help flesh out any missing pieces you need when i get time, so do file issues.

**Comment by bitdivision** [comment]
Lovely. Thanks very much.

I don't know if I'll definitely be using it, but will let you know if I run into anything.
